server:
  port: 8080
  address: 192.168.31.60
  context-path: /wms

logging:
  level:
    org:
       springframework:
           security: DEBUG
    root: INFO

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://yyt8812.gnway.cc:1344;databaseName=yytsy
    username: sa
    password: yyt@123
#    url: jdbc:sqlserver://localhost;databaseName=yyt
#    username: sa
#    password: zhupeng123
    name: wms
    type: com.alibaba.druid.pool.DruidDataSource
    #连接池的配置信息
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

security:
  basic:
    enabled: false
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.teeny.wms.web.model.dto